# SPDX-FileCopyrightText: 2022 Helsing GmbH
#
# SPDX-License-Identifier: Apache-2.0

[package]
authors = ["Tpt <thomas@pellissier-tanon.fr>"]
description = "Auto-formatter for RDF Turtle"
edition = "2021"
keywords = ["pretty-print", "rdf", "turtle"]
categories = ["command-line-utilities", "development-tools", "value-formatting"]
license = "Apache-2.0"
name = "turtlefmt"
readme = "README.md"
repository = "https://github.com/helsing-ai/turtlefmt"
rust-version = "1.81.0"
version = "0.1.2"

[lints.rust]
rust_2021_compatibility = { level = "warn", priority = -1 }

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
wildcard_enum_match_arm = "warn"
# string_slice = "warn"
# indexing_slicing = "warn"
clone_on_ref_ptr = "warn"
try_err = "warn"
#shadow_reuse = "warn"
empty_structs_with_brackets = "warn"
else_if_without_else = "warn"
use_debug = "warn"
print_stdout = "warn"
print_stderr = "warn"
#default_trait_access = "allow"
#option_if_let_else = "allow"
struct_excessive_bools = "allow"

[dependencies]
const_format = { version = "0.2", default-features = false }
clap = { version = "4.5", default-features = false, features = ["std", "derive"] }
diffy = { version = "0.4", default-features = false }
oxrdf = { version = "0.2", default-features = false }
oxttl = { version = "0.1", default-features = false }
rdf-canon = { version = "0.15", default-features = false }
regex = { version = "1.11", default-features = false }
thiserror = { version = "2.0", default-features = false }
tree-sitter = { version = "0.25", default-features = false, features = ["std"] }

[dev-dependencies]
oxrdf = { version = "0.2", default-features = false }
oxttl = { version = "0.1", default-features = false }
pretty_assertions = "1.4"
reqwest = { version = "0.12", default-features = false, features = ["blocking"] }

[build-dependencies]
cc = { version = "1.1", default-features = false }
tree-sitter-generate = { version = "0.25", default-features = false }
