[package]
authors = ["Tpt <thomas@pellissier-tanon.fr>"]
description = "Auto-formatter for RDF Turtle"
edition = "2021"
keywords = ["pretty-print", "rdf", "turtle"]
categories = ["command-line-utilities", "development-tools", "value-formatting"]
license = "Apache-2.0"
name = "turtlefmt"
readme = "README.md"
repository = "https://github.com/helsing-ai/turtlefmt"
rust-version = "1.81.0"
version = "0.1.2"

[lints.rust]
rust_2021_compatibility = { level = "warn", priority = -1 }

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
wildcard_enum_match_arm = "warn"
# string_slice = "warn"
# indexing_slicing = "warn"
clone_on_ref_ptr = "warn"
try_err = "warn"
#shadow_reuse = "warn"
empty_structs_with_brackets = "warn"
else_if_without_else = "warn"
use_debug = "warn"
print_stdout = "warn"
print_stderr = "warn"
#default_trait_access = "allow"
#option_if_let_else = "allow"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
diffy = "0.4"
tree-sitter = "0.25"

[dev-dependencies]
oxrdf = "0.2"
oxttl = "0.1"
pretty_assertions = "1.4"
reqwest = { version = "0.12", default-features = false, features = ["blocking"] }

[build-dependencies]
cc = "1.1"
tree-sitter-generate = "0.25"
