[package]
authors = ["Tpt <thomas@pellissier-tanon.fr>"]
description = "Auto-formatter for RDF Turtle"
edition = "2021"
keywords = ["pretty-print", "rdf", "turtle"]
categories = ["command-line-utilities", "development-tools", "value-formatting"]
license = "Apache-2.0"
name = "turtlefmt"
readme = "README.md"
repository = "https://github.com/helsing-ai/turtlefmt"
rust-version = "1.81.0"
version = "0.1.2"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.16", features = ["derive"] }
diffy = "0.4.0"
tree-sitter = "0.24.6"

[dev-dependencies]
oxrdf = "0.2.3"
oxttl = "0.1.3"
pretty_assertions = "1.4"
reqwest = { version = "0.12.7", default-features = false, features = ["blocking"] }

[build-dependencies]
cc = "1.1.15"
tree-sitter-generate = "0.24.6"
